# Generated by Django 2.1.3 on 2018-12-01 15:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('package_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('name_translated', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.CharField(max_length=20)),
                ('datastore_active', models.BooleanField(default=False)),
                ('hash', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('mimetype', models.CharField(blank=True, max_length=20, null=True)),
                ('mimetype_inner', models.CharField(blank=True, max_length=20, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=None)),
                ('url', models.URLField(max_length=250)),
                ('url_type', models.CharField(blank=True, max_length=20, null=True)),
                ('data_quality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('revision_id', models.UUIDField(blank=True, null=True)),
                ('cache_url', models.URLField(blank=True, null=True)),
                ('cache_last_updated', models.DateTimeField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
